# Школа глубокого обучения

<a href="https://mipt.ru/science/labs/laboratoriya-neyronnykh-sistem-i-glubokogo-obucheniya/"><img align="right" src="https://avatars1.githubusercontent.com/u/29918795?v=4&s=200" alt="DeepHackLab" style="position:relative;top:-40px;right:10px;height:100px;" /></a>



### Физтех-Школа Прикладной математики и информатики МФТИ 
### Лаборатория нейронных сетей и глубокого обучения (DeepHackLab)

## Домашнее задание 1
### Основы Python и пакет NumPy
---


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задача 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [7]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j), здесь i -- число строк,
# j -- число столбцов.
a = np.random.sample((3,3))
b = np.random.sample((3,3))
print(a)
print(b)

[[ 0.85960707  0.37123034  0.61993874]
 [ 0.08567991  0.44038004  0.83198939]
 [ 0.18862522  0.87543181  0.71546386]]
[[ 0.2829591   0.50188716  0.93870564]
 [ 0.35001855  0.33599555  0.76199722]
 [ 0.56258582  0.70208132  0.59862756]]


In [8]:
def mult(a, b):
    d = []
    for x in range(len(a[0])):
        d.append([])
        for y in range(len(b[0])):
            d[x].append(0)
            for i in range(len(a)):
                d[x][y] += a[x][i]*b[i][y]
    return d

In [9]:
def np_mult(a, b):
    return a@b

In [10]:
%%time
mult(a,b)

Wall time: 0 ns


[[0.72193988805014819, 0.99140490987714935, 1.4609069110978163],
 [0.64645052312289497, 0.77509159301816344, 0.91404836574899628],
 [0.76230041653164915, 0.89112358740673536, 1.272436553247517]]

In [11]:
%%time
np_mult(a,b)

Wall time: 605 ms


array([[ 0.72193989,  0.99140491,  1.46090691],
       [ 0.64645052,  0.77509159,  0.91404837],
       [ 0.76230042,  0.89112359,  1.27243655]])

### Задача 2
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость, объясните результат.

In [12]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    return np.sum(A)/A.size

In [13]:
# функция без NumPy
def stupid_sec_av(A):
    S = 0;
    for i in range(len(A)):
        S+=A[i]
    S=S/len(A)
    return S

# зададим некоторую последовательность и проверим ее на ваших функциях. 
# Первая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10 ** 7) 

%time S1 = sec_av(A)
%time S2 = stupid_sec_av(A)
#проверим корректность:
np.abs(S1 - S2).sum()

Wall time: 32 ms
Wall time: 8.34 s


5.0626169922907138e-14

### Задача 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все четные элементы исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться без изменений. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке. 

In [14]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    X_ = X.copy()
    X_[0::2] = a
    X_[1::2] = X_[1::2]**3
    X_ = X_[::-1]
    Y = np.hstack((X,X_))
    Y = Y[::-1]
    return Y

In [15]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
    l = len(X)
    X_ = [X[i] for i in range(l)]
    for i in range(0,l,2):
        X_[i] = a
    for i in range(1,l,2):
        X_[i] = X_[i]**3
    X_ = X_[::-1]
    Y = [X[i] for i in range(l)]
    Y += X_
    Y = Y[::-1]
    return Y

In [16]:
X = sps.uniform.rvs(size=10 ** 7) 
# здесь код эффективнее примерно в 20 раз. 
# если Вы вдруг соберетесь печатать массив без np -- лучше сначала посмотрите на его размер
%time S1 = transformation(X)
%time S2 = stupid_transformation(X)
# проверим корректность:
np.abs(S1 - S2).sum()

Wall time: 1.32 s
Wall time: 23.4 s


0.0

Почему методы ***numpy*** оказываются эффективнее?

In [251]:
Потому что c Numpy работа происходит с массивами, а не списками, что в разы увеличивает производительность. 
Потому что в списках для получения n-го элемента, потребуется последовательно перебрать n-1 указателям.

SyntaxError: invalid syntax (<ipython-input-251-17836fb1fe84>, line 1)

## Дополнительные задачи

Дополнительные задачи подразумевают, что Вы самостоятельно разберётесь в некоторых функциях ***numpy***, чтобы их сделать.  

Эти задачи не являются обязательными, но могут повлиять на Ваш рейтинг в лучшую сторону (точные правила учёта доп. задач будут оглашены позже).

### Задача 4*

Дана функция двух переменных: $f(x, y) = sin(x)cos(y)$ (это просто такой красивый 3D-график), а также дана функция для отрисовки $f(x, y)$ (`draw_f()`), которая принимает на вход двумерную сетку, на которой будет вычисляться функция.  

Вам нужно разобраться в том, как строить такие сетки (подсказка - это одна конкретная функция ***numpy***), и подать такую сетку на вход функции отрисовки.

In [252]:
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

def f(x, y):
    '''Функция двух переменных'''
    return np.sin(x) * np.cos(y)

def draw_f(grid_x, grid_y):
    '''Функция отрисовки функции f(x, y)'''
    fig = plt.figure(figsize=(10, 8))
    ax = Axes3D(fig)
    ax.plot_surface(grid_x, grid_y, f(grid_x, grid_y), cmap='inferno')
    plt.show()

In [ ]:
grid_x, grid_y = # Ваш код здесь

draw_f(gridx, gridy)

### Задача 5*

Вам дана картинка. При загрузке её размерность равна 3: **(w, h, num_channels)**, где **w** - ширина картинки в пикселях, **h** - высота картинки в пикселях, **num_channels** - количество каналов *(R, G, B, alpha)*.

Вам нужно "развернуть" картинку в одномерный массив размера w \* h \* num_channels, написав **одну строку кода**.

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
path_to_image = './image.png'
image_array = plt.imread(path_to_image)
plt.imshow(image_array);

In [ ]:
flat_image_array = # Ваш код здесь

In [ ]:
# здесь выведите размер нового массива